# version: '3'
# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#   db:
#     image: lms:latest
#     environment:
#       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#       MYSQL_DATABASE: django_lms
#       MYSQL_USER: root
#       MYSQL_PASSWORD: 
#       MYSQL_ROOT_PASSWORD: 
#     volumes:
#       - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
#     ports:
#       - "3306:3306"
# volumes:
#   dbdata:


version: "3.8"
services:
  frontend:
    build: ./quizUi
    ports:
      - "3000:3000"
    volumes:
      - ./quizUi:/app
      - ./lms/data/mysql/db:/var/lib/mysql
  app:
    build: ./lms
    volumes:
      - ./lms:/app
    ports:
      - "8000:8000"
    # image: app:django
    container_name: django_container
    # command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db 
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'django_lms'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - "3306:3306"
    volumes:
      - ./lms/datap/mysql/db:/var/lib/mysql